### ISSUE TITLE
Typo in max30102_for_stm32_hal.c, function void max30102_read_fifo(max30102_t *obj), line 367

### ISSUE THREAD

**Issue by nktvslnk** [eepj/MAX30102_for_STM32_HAL#3]
There should be 
uint32_t ir_sample = ((uint32_t)(sample[0] << 16) | (uint32_t)(sample[1] << 8) | (uint32_t)(sample[**2**])) & 0x3ffff;
instead of
uint32_t ir_sample = ((uint32_t)(sample[0] << 16) | (uint32_t)(sample[1] << 8) | (uint32_t)(sample[**3**])) & 0x3ffff;

**Comment by eepj** [comment]
Thank you for reporting this. Fixed in 8e4ec9e0e6083f581a01c02b64b773d4cedde043.
