### ISSUE TITLE
MAX30101 support ?

### ISSUE THREAD

**Issue by boumatsu** [eepj/MAX30102_for_STM32_HAL#4]
Does this driver support the MAX30101 also ? https://www.analog.com/en/products/max30101.html

**Comment by eepj** [comment]
The register maps of the two ICs are very similar, but I am not sure what the behavior of the MAX30101 is when a reserved register is read. So unfortunately my guess is that it doesn't.

**Comment by boumatsu** [comment]
Okay thank you very much
